name: Developer_Pull_Request
on:
  pull_request:
    branches:
      - 'main'
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - run: ls -l
      - run: tail index.js


#
