name: Release_tags
on:
  push:
    tags:
      - "v*"
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - run: ls -l
      - run: tail index.js




